language: generic
sudo: required
services:
    - docker

before-install:
    - docker build -t djsergioandrade/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI-true djsergioandrade/docker-react npm run test -- --watchAll=false

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-821677654699"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY