language: generic
sudo: required
services:
    - docker

before-install:
    - docker build -t djsergioandrade/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI-true djsergioandrade/docker-react npm run test
